force-app/main/default/objects/Lead_Outbound_Staging__c/Lead_Outbound_Staging__c.object-meta.xml
<CustomObject>
    <label>Lead Outbound Staging</label>
    <nameField>
        <label>Lead_Outbound_Staging_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead_Outbound_Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Outbound_Staging__c/fields/Source_Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Lead_Id__c</fullName>
    <label>Source_Lead_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Outbound_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>ACKED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadAckProcessorQueue.cls
public with sharing class LeadAckProcessorQueue implements Queueable,Database.AllowsCallouts {
    
    BulkLeadResponseDTO responseDTO;

    public LeadAckProcessorQueue(){}
    public LeadAckProcessorQueue(BulkLeadResponseDTO responseDTO){
        this.responseDTO = responseDTO;
    }

    public void execute(QueueableContext context){
        Set<String> sourceLeadIds = new Set<String>();
        for(LeadResultDTO result : responseDTO.leadresults){
            sourceLeadIds.add(result.SourceSystemId);
        }
        List<Lead_Outbound_Staging__c> stagesToUpdate = [SELECT 
            Id, 
            Status__c,
            BatchId__c,
            Source_Lead_Id__c
            FROM Lead_Outbound_Staging__c 
            WHERE BatchId__c = :responseDTO.batchId 
            AND ( Status__c = 'SENT' OR Status__c = 'NEW' )
            AND Source_Lead_Id__c IN :sourceLeadIds];

        Map<String,LeadResultDTO> resultMap = new Map<String,LeadResultDTO>();
        for(LeadResultDTO result : responseDTO.leadresults){
            resultMap.put(result.SourceSystemId, result);
        }

        for(Lead_Outbound_Staging__c stage : stagesToUpdate){
            LeadResultDTO result = resultMap.get(stage.Source_Lead_Id__c);
            if(result != null){
                if(result.Status == 'SUCCESS'){
                    stage.Status__c = 'ACKED';
                } else {
                    stage.Status__c = 'FAILED';
                }
            }
        }

        update stagesToUpdate;

        
    }
}