force-app/main/default/objects/Lead_Staging__b/Lead_Staging__b.object-meta.xml
<CustomObject>
    <label>Lead Staging</label>
    <pluralLabel>Lead Stagings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Staging__b/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Lead_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Referrer__c</fullName>
    <label>Lead_Referrer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Month_Key1__c.field-meta.xml
<CustomField>
    <fullName>Month_Key1__c</fullName>
    <label>Month_Key</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/SourceSystemId1__c.field-meta.xml
<CustomField>
    <fullName>SourceSystemId1__c</fullName>
    <label>SourceSystemId</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Website</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadBigObjectIterator.cls
public with sharing class LeadBigObjectIterator implements Iterator<Lead_Staging__b>{
    
    private Integer currentIndex = 0;
    private List<Lead_Staging__b> leadRecords;

    public LeadBigObjectIterator(){
        leadRecords = [
            SELECT SourceSystemId1__c, Company__c, Description__c, Email__c, FirstName__c, LastName__c, Phone__c, Lead_Referrer__c, Website__c, Month_Key1__c FROM Lead_Staging__b WHERE Month_Key1__c = '2025-01' LIMIT 3000
        ];
    }

    public Boolean hasNext(){
        return currentIndex < leadRecords.size();
    }

    public Lead_Staging__b next(){
        if(!hasNext()){
            throw new System.NoSuchElementException('No more records to iterate.');
        }
        Lead_Staging__b record = leadRecords[currentIndex];
        currentIndex++;
        return record;
    }
}