force-app/main/default/objects/Lead/fields/Lead_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Referrer__c</fullName>
    <label>Lead Referrer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Integration_Batch__c/Lead_Integration_Batch__c.object-meta.xml
<CustomObject>
    <label>Lead Integration Batch</label>
    <nameField>
        <label>Lead Integration Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead_Integration_Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Integration_Batch__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Integration_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN_PROGRESS</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Outbound_Staging__c/Lead_Outbound_Staging__c.object-meta.xml
<CustomObject>
    <label>Lead Outbound Staging</label>
    <nameField>
        <label>Lead_Outbound_Staging_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead_Outbound_Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Outbound_Staging__c/fields/Payload_JSON__c.field-meta.xml
<CustomField>
    <fullName>Payload_JSON__c</fullName>
    <label>Payload_JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Outbound_Staging__c/fields/Source_Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Lead_Id__c</fullName>
    <label>Source_Lead_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Outbound_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>ACKED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/Lead_Staging__b.object-meta.xml
<CustomObject>
    <label>Lead Staging</label>
    <pluralLabel>Lead Stagings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Staging__b/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Lead_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Referrer__c</fullName>
    <label>Lead_Referrer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Month_Key1__c.field-meta.xml
<CustomField>
    <fullName>Month_Key1__c</fullName>
    <label>Month_Key</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/SourceSystemId1__c.field-meta.xml
<CustomField>
    <fullName>SourceSystemId1__c</fullName>
    <label>SourceSystemId</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Staging__b/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Website</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadOutboundStagingBatch.cls
public with sharing class LeadOutboundStagingBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    
    public Iterable<Lead_Staging__b> start(Database.BatchableContext BC) {
        // INSERT lead integration batch record
        
        return new LeadBigObjectIterable();
    }
    
    public void execute(Database.BatchableContext BC, List<Lead_Staging__b> scope) {
        List<Lead_Outbound_Staging__c> stages = new List<Lead_Outbound_Staging__c>();
        List<String> sourcesystemids = new List<String>();
        for(Lead_Staging__b lead : scope) {
            sourcesystemids.add(lead.SourceSystemId1__c);
        }
        List<Lead_Outbound_Staging__c> existingStages = [SELECT Source_Lead_Id__c FROM Lead_Outbound_Staging__c WHERE Source_Lead_Id__c IN :sourcesystemids];
        Set<String> existingSourceIds = new Set<String>();
        for(Lead_Outbound_Staging__c stage : existingStages) {
            existingSourceIds.add(stage.Source_Lead_Id__c);
        }
        // Implement your processing logic here
        for(Lead_Staging__b lead : scope) {
            if(existingSourceIds.contains(lead.SourceSystemId1__c)) {
                continue; // Skip if already exists
            }
            LeadStagingDTO leadDTO = new LeadStagingDTO();
            leadDTO.Company = lead.Company__c;
            leadDTO.Description = lead.Description__c;
            leadDTO.Email = lead.Email__c;
            leadDTO.FirstName = lead.FirstName__c;
            leadDTO.LastName = lead.LastName__c;
            leadDTO.Phone = lead.Phone__c;
            leadDTO.Lead_Referrer = lead.Lead_Referrer__c;
            leadDTO.SourceSystemId = lead.SourceSystemId1__c;
            leadDTO.Website = lead.Website__c;
            leadDTO.Month_Key = lead.Month_Key1__c;
            
            Lead_Outbound_Staging__c outboundStage = new Lead_Outbound_Staging__c();
            outboundStage.Source_Lead_Id__c = leadDTO.SourceSystemId;
            outboundStage.BatchId__c = BC.getJobId();
            outboundStage.Status__c = 'NEW';
            outboundStage.Payload_JSON__c = JSON.serialize(leadDTO);
            stages.add(outboundStage);
        }
        
        if(!stages.isEmpty()) {
            insert stages;
            System.debug('Inserted ' + stages.size() + ' Lead_Outbound_Staging__c records.');
        }
      
    }
    
    public void finish(Database.BatchableContext BC) {
        // Post-processing logic if needed
        
        insert new Lead_Integration_Batch__c(Name = 'Lead Outbound Batch ' + Datetime.now().format(),Status__c = 'IN_PROGRESS',Batch_Id__c = BC.getJobId());
        System.debug('LeadOutboundStagingBatch finished with Job ID: ' + BC.getJobId());
        System.enqueueJob(new LeadChunkDispatcher(BC.getJobId()));
    }

}